const types = {
  GET_POSTS_START: 'GET_POSTS_START',
  GET_POSTS_SUCCESS: 'GET_POSTS_SUCCESS',
  GET_POSTS_ERROR: 'GET_POSTS_ERROR',

  ADD_COMMENT_START: 'ADD_COMMENT_START',
  ADD_COMMENT_SUCCESS: 'ADD_COMMENT_SUCCESS',
  ADD_COMMENT_ERROR: 'ADD_COMMENT_ERROR',

  GET_COMMENT_START: 'GET_COMMENT_START',
  GET_COMMENT_SUCCESS: 'GET_COMMENT_SUCCESS',
  GET_COMMENT_ERROR: 'GET_COMMENT_ERROR',

  GET_POST_FROM_ID_START: 'GET_POST_FROM_ID_START',
  GET_POST_FROM_ID_SUCCESS: 'GET_POST_FROM_ID_SUCCESS',
  GET_POST_FROM_ID_ERROR: 'GET_POST_FROM_ID_ERROR',

  PUT_POST_START: 'PUT_POST_START',
  PUT_POST_SUCCESS: 'PUT_POST_SUCCESS',
  PUT_POST_ERROR: 'PUT_POST_ERROR',

  ADD_POST_START: 'ADD_POST_START',
  ADD_POST_SUCCESS: 'ADD_POST_SUCCESS',
  ADD_POST_ERROR: 'ADD_POST_ERROR',

  DELETE_POST_START: 'DELETE_POST_START',
  DELETE_POST_SUCCESS: 'DELETE_POST_SUCCESS',
  DELETE_POST_ERROR: 'DELETE_POST_ERROR',

  EDIT_POST_START: 'EDIT_POST_START',
  EDIT_POST_SUCCESS: 'EDIT_POST_SUCCESS',
  EDIT_POST_ERROR: 'EDIT_POST_ERROR',

  OPEN_MODAL: 'OPEN_MODAL',
  CLOSE_MODAL: 'CLOSE_MODAL',
};

export default types;
